#_welcome:
 #   path:     /
  #  defaults: { _controller: AcmeDemoBundle:Welcome:index }

#_demo_secured:
 #   resource: "@AcmeDemoBundle/Controller/SecuredController.php"
  #  type:     annotation

_store:
    resource: "@AcmeStoreBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /store
